# ChatGPT -> MATLAB Automation Workflow

param(
    [string]$UserPrompt = "generate a simple FFT code",
    [string]$OutputDir = "$env:USERPROFILE\Documents\MATLAB\AutoGenerated",
    [int]$MaxRetries = 5
)

$TempCodeFile = "$env:TEMP\chatgpt_generated.m"
$MatlabLogFile = "$env:TEMP\matlab_run.log"
$MatlabErrFile = "$env:TEMP\matlab_error.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = if ($Level -eq "ERROR") { "Red" } elseif ($Level -eq "SUCCESS") { "Green" } elseif ($Level -eq "WARN") { "Yellow" } else { "White" }
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
}

function Find-Matlab {
    $paths = @(
        "D:\Program Files\MATLAB\R2025b\bin\matlab.exe",
        "C:\Program Files\MATLAB\R2023b\bin\matlab.exe",
        "C:\Program Files\MATLAB\R2023a\bin\matlab.exe",
        "C:\Program Files\MATLAB\R2022b\bin\matlab.exe",
        "C:\Program Files\MATLAB\R2021b\bin\matlab.exe",
        "C:\Program Files\MATLAB\R2020b\bin\matlab.exe"
    )
    foreach ($p in $paths) { if (Test-Path $p) { return $p } }
    return $null
}

function Run-MatlabScript {
    param([string]$MFilePath)
    
    $matlabExe = Find-Matlab
    if (-not $matlabExe) {
        Write-Log "MATLAB not found. Please install MATLAB or add to PATH." -Level "ERROR"
        return $null
    }
    
    Write-Log "Using MATLAB: $matlabExe"
    
    if (Test-Path $MatlabLogFile) { Remove-Item $MatlabLogFile -Force }
    if (Test-Path $MatlabErrFile) { Remove-Item $MatlabErrFile -Force }
    
    $scriptDir = Split-Path $MFilePath -Parent
    $scriptName = Split-Path $MFilePath -Leaf
    $matlabCmd = "cd('$scriptDir'); run('$scriptName'); exit;"
    
    try {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName = $matlabExe
        $psi.Arguments = "-nosplash -nodesktop -batch `"$matlabCmd`""
        $psi.RedirectStandardOutput = $true
        $psi.RedirectStandardError = $true
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow = $true
        
        $proc = [System.Diagnostics.Process]::Start($psi)
        $proc.WaitForExit(300000) | Out-Null
        
        if ($proc.HasExited) {
            $exitCode = $proc.ExitCode
            $output = $proc.StandardOutput.ReadToEnd()
            $errorOutput = $proc.StandardError.ReadToEnd()
            
            $output | Out-File -FilePath $MatlabLogFile -Encoding UTF8
            $errorOutput | Out-File -FilePath $MatlabErrFile -Encoding UTF8
            
            Write-Log "MATLAB exit code: $exitCode"
            
            return @{
                ExitCode = $exitCode
                Output = $output
                ErrorOutput = $errorOutput
                Success = ($exitCode -eq 0)
            }
        } else {
            $proc.Kill()
            Write-Log "MATLAB timeout" -Level "ERROR"
            return $null
        }
    }
    catch {
        Write-Log "MATLAB run failed: $_" -Level "ERROR"
        return $null
    }
}

function Save-MatlabCode {
    param([string]$Code, [string]$FilePath)
    $dir = Split-Path -Parent $FilePath
    if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllText($FilePath, $Code, [System.Text.Encoding]::UTF8)
    Write-Log "Code saved to: $FilePath" -Level "SUCCESS"
    return $true
}

# Main
Write-Log "========== ChatGPT -> MATLAB Workflow Started =========="
Write-Log "Prompt: $UserPrompt"
Write-Log "Output: $OutputDir"
Write-Log ""

$retryCount = 0
$lastError = ""

while ($retryCount -lt $MaxRetries) {
    $retryCount++
    Write-Log "===== Attempt $retryCount of $MaxRetries ====="
    
    if ($retryCount -eq 1) {
        Write-Log "Step 1: Send prompt to ChatGPT (manual)"
        Write-Log "Please paste the MATLAB code generated by ChatGPT below:"
    } else {
        Write-Log "Step 7: Error detected, please send to ChatGPT for fix"
        Write-Log "Error: $lastError"
        Write-Log "Paste the corrected MATLAB code below:"
    }
    
    $generatedCode = Read-Host "MATLAB code (Enter for test code)"
    
    if ([string]::IsNullOrWhiteSpace($generatedCode)) {
        $generatedCode = @'
% Test FFT code
Fs = 1000;
T = 1/Fs;
L = 1500;
t = (0:L-1)*T;
x = sin(2*pi*50*t) + 0.5*sin(2*pi*120*t);
y = fft(x);
P2 = abs(y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2*P1(2:end-1);
f = Fs*(0:(L/2))/L;
plot(f,P1)
title('Single-Sided Amplitude Spectrum')
xlabel('f (Hz)')
ylabel('|P1(f)|')
grid on
'@
        Write-Log "[Demo mode] Using test code"
    }
    
    # Save code
    Save-MatlabCode -Code $generatedCode -FilePath $TempCodeFile
    
    # Run MATLAB
    Write-Log "Running MATLAB..."
    $result = Run-MatlabScript -MFilePath $TempCodeFile
    
    if ($null -eq $result) {
        Write-Log "MATLAB failed to run" -Level "ERROR"
        continue
    }
    
    if ($result.Success) {
        Write-Log "MATLAB ran successfully!" -Level "SUCCESS"
        
        # Save to final location
        if (!(Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }
        $fileName = Split-Path $TempCodeFile -Leaf
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $destFile = Join-Path $OutputDir "$timestamp`_$fileName"
        Copy-Item $TempCodeFile $destFile -Force
        Write-Log "File saved to: $destFile" -Level "SUCCESS"
        
        Write-Log "========== Workflow Complete! =========="
        exit 0
    } else {
        $lastError = $result.ErrorOutput + $result.Output
        Write-Log "MATLAB error: $lastError" -Level "ERROR"
    }
    
    Write-Log ""
}

Write-Log "Max retries reached. Workflow terminated." -Level "ERROR"
exit 1
